### ISSUE TITLE
blank screen after unpausing

### ISSUE THREAD

**Issue by alfonzo90** [TimIsOverpowered/poke-frontend#5]
from my experience this only happened on older vods ex: in page 32. 

after watching for a bit or jumping to a random point, pausing and unpausing, the moment i unpause the entire screen turns blank and i have to basically reset the page.

**Comment by TimIsOverpowered** [comment]
Can you leave a link to the vod that it happened on?

**Comment by TimIsOverpowered** [comment]
Should be fixed. Let me know if it fixes your problem.
