### ISSUE TITLE
Oh no something went wrong

### ISSUE THREAD

**Issue by Jojjojoojooj** [TimIsOverpowered/poke-frontend#9]
When i try to link my twitch the website doesnt allow me
![image](https://github.com/TimIsOverpowered/poke-frontend/assets/136396774/68a0c125-fb57-4b4b-b82b-e6e1af3bed0f)
![image](https://github.com/TimIsOverpowered/poke-frontend/assets/136396774/df739e93-47c3-434a-bad6-36d783b6151a)

**Comment by TimIsOverpowered** [comment]
Could you try again?

**Comment by Jojjojoojooj** [comment]
> Could you try again?

Nope still not working it now just reloads the page without linking my account. The screenshots above arent appearing anymore

**Comment by Jojjojoojooj** [comment]
It is now working!
